version: "3"
services:
  mongodb:
    container_name: ippl-mongo
    image: mongo
    restart: unless-stopped
    ports:
      - $DB_PORT:27017
    env_file: ./.env
    environment:
      MONGODB_USER: $DB_USERNAME
      MONGODB_PASSWORD: $DB_PASSWORD
      MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
      MONGO_INITDB_DATABASE: $DB_NAME
    volumes:
      - db:/data/db
    networks:
      - app-network

  mongo-express:
    container_name: ippl-mongo-express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file: ./.env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongodb:27017/$DB_NAME
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - app-network

  minio:
    container_name: ippl-minio
    image: quay.io/minio/minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    networks:
      - app-network

volumes:
  db:

networks:
  web:
    external: true
  app-network:
    external: false
    driver: bridge
