name: SINDU-BE__CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            echo "changing directory"
            cd ~/apps/ticketing-backend
            echo "pulling latest changes"
            git pull origin main
            echo "updating env"
            echo "${{ secrets.ENV_FILE }}" > .env
            echo "rebuild apps"
            docker-compose -f docker-compose-prod.yaml up --build -d --remove-orphans
            exit
